### ISSUE TITLE
DB accepts negative values

### ISSUE THREAD

**Issue by migsszz** [miguelflores-0906/CSSWENG-GROUP-4-ADMIN-SIDE#2]
**Summary:**
Database accepts negative values instead of parsing into non-negative values.
**Steps to Reproduce:**
Add negative values to either receipt no. or price
**Expected Results:**
Negative values are parsed into non-negative values
**Actual Results:**
Negative values are accepted.
**Recommendation:**
Use a function such as Math.abs() to fix any negative value errors. 

| Info  | Value |
| ------------- | ------------- |
| Browser  | Google Chrome |
| Screen Size  | 1920x1080 |
| Zoom  | 100% |

![error2](https://user-images.githubusercontent.com/33576804/133310344-8a47ce2b-e3e4-4da9-aa21-8877c94b0801.PNG)

**Comment by miguelflores-0906** [comment]
I've fixed the negative values being added and now the form prompts the user to input a number greater than or equal to zero. As for the receipt number, do you think receipts can have characters such as letters and hyphens? if the leading character would be a hyphen do you think we should still accept it or no? I can make it so that the field only accepts numbers if that is what we're going for.

**Comment by migsszz** [comment]
Good question, I was always under the impression that receipt nos were generated based on date and time, so I'd say characters are a no go. It's ultimately up to the designers but that's what I think.

**Comment by miguelflores-0906** [comment]
Alright, for now, I made it so that it only accepts numbers and 'n/a' in the off chance that there is no receipt number

**Comment by migsszz** [comment]
On Add Revenue: Same problem occurs.

**Comment by miguelflores-0906** [comment]
Went over my head, mb, should be goods
